import type { AnnotatedLinePoint, BarChartPoint, StoryArcSeries } from './types';

export const storyArcData: StoryArcSeries[] = [
  {
    name: 'Interstellar',
    color: '#2d3748',
    data: [
      { x: 1, value: -2, label: 'Earth dying / Dust storms' },
      { x: 2, value: -1, label: "Murph's ghost" },
      { x: 3, value: 2, label: 'Discovering NASA' },
      { x: 4, value: 0, label: 'The mission choice' },
      { x: 5, value: -5, label: 'Leaving Murph behind' },
      { x: 6, value: 4, label: 'Launch' },
      { x: 7, value: 3, label: 'Wormhole travel' },
      { x: 8, value: 0, label: "Miller's Planet" },
      { x: 9, value: -6, label: '23 years lost' },
      { x: 10, value: -4, label: 'Messages from home' },
      { x: 11, value: -1, label: "Mann's Planet debate" },
      { x: 12, value: -7, label: "Dr. Mann's betrayal" },
      { x: 13, value: -5, label: 'Docking sequence' },
      { x: 14, value: -3, label: 'Slingshot maneuver' },
      { x: 15, value: -8, label: 'Cooper detaches' },
      { x: 16, value: 5, label: 'Inside the Tesseract' },
      { x: 17, value: 7, label: 'Communicating with Murph' },
      { x: 18, value: 6, label: 'Murph solves gravity' },
      { x: 19, value: 3, label: 'Tesseract closes' },
      { x: 20, value: 4, label: 'Cooper Station rescue' },
      { x: 21, value: 5, label: 'Reuniting with Murph' },
      { x: 22, value: 2, label: 'Bittersweet goodbye' },
      { x: 23, value: 6, label: 'Stealing the ship' },
      { x: 24, value: 7, label: 'Finding Brand' },
    ],
  },
  {
    name: 'Baseline',
    color: '#a0aec0',
    strokeDasharray: '5,5',
    data: [
      { x: 1, value: 1, label: 'Opening image' },
      { x: 2, value: 2, label: 'Setup' },
      { x: 3, value: 1, label: 'Theme stated' },
      { x: 4, value: -3, label: 'Inciting incident' },
      { x: 5, value: -5, label: 'Debate' },
      { x: 6, value: 0, label: 'Break into Act II' },
      { x: 7, value: 2, label: 'B story' },
      { x: 8, value: -2, label: 'Fun and games begins' },
      { x: 9, value: -4, label: 'Rising complications' },
      { x: 10, value: -6, label: 'Mid-crisis setup' },
      { x: 11, value: -3, label: 'Hope spot' },
      { x: 12, value: 0, label: 'Midpoint (reversal)' },
      { x: 13, value: 1, label: 'Escalation' },
      { x: 14, value: -1, label: 'Tension mounts' },
      { x: 15, value: -3, label: 'Bad guys close in' },
      { x: 16, value: -8, label: 'All is lost' },
      { x: 17, value: -6, label: 'Dark night of the soul' },
      { x: 18, value: -2, label: 'Break into Act III' },
      { x: 19, value: 3, label: 'Final approach' },
      { x: 20, value: 6, label: 'Climax' },
      { x: 21, value: 8, label: 'Payoff' },
      { x: 22, value: 6, label: 'Falling action' },
      { x: 23, value: 4, label: 'Denouement' },
      { x: 24, value: 7, label: 'Final image' },
    ],
  },
];

export const annotatedLineData: AnnotatedLinePoint[] = [
  { quarter: 'Q1', value: 24000 },
  { quarter: 'Q1_mid', value: 22000 },
  { quarter: 'Q2', value: 32000 },
  { quarter: 'Q2_mid', value: 43000 },
  { quarter: 'Q3', value: 48000 },
  { quarter: 'Q3_mid', value: 34000 },
  { quarter: 'Q4', value: 38000 },
];

export const barChartData: BarChartPoint[] = [
  { day: 'Mon', dataset1: 25, dataset2: 50 },
  { day: 'Tue', dataset1: 15, dataset2: 60 },
  { day: 'Wed', dataset1: 45, dataset2: 85 },
  { day: 'Thu', dataset1: 20, dataset2: 55 },
  { day: 'Fri', dataset1: 22, dataset2: 58 },
  { day: 'Sat', dataset1: 10, dataset2: 65 },
  { day: 'Sun', dataset1: 5, dataset2: 30 },
];
